DEFAULT_ERROR="Something went wrong!"
LEAVE_SUCCESS_MSG="your leave has been added successfully"
DUPLICATE_LEAVE_RAISE_ERROR="Leave are already added"
DUPLICATE_LEAVE_ERROR="{'non_field_errors': [ErrorDetail(string='Leave are already added', code='invalid')]}"
DUPLICATE_LEAVE_MSG="Leave of the date already exist"
DUPLICATE_LEAVES_MSG="some days of your leaves are already added by you"
INVALID_DATE_RAISE_ERROR="Invalid Date"
INVALID_DATE_ERROR="{'non_field_errors': [ErrorDetail(string='Invalid Date', code='invalid')]}"
INVALID_DATE_MSG="end date should be greater than the start date"
