# Generated by Django 4.0.1 on 2022-01-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Updated_date',
            new_name='updated_date',
        ),
    ]
